/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  publishedAt?: string;
  slug?: Slug;
  subtitle?: string;
  author?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'author';
  };
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'blogCategory';
  };
  mainImage?: BlockImage;
  minRead?: number;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type BlockImage = {
  _type: 'blockImage';
  asset?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  mainImage?: BlockImage;
  body?: BlockContent;
};

export type BlogCategory = {
  _id: string;
  _type: 'blogCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type UtilityPage = {
  _id: string;
  _type: 'utilityPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: BlockContent;
};

export type Faq = {
  _id: string;
  _type: 'faq';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type TeamMember = {
  _id: string;
  _type: 'teamMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  slug?: Slug;
  mainImage?: BlockImage;
  instaLink?: string;
  body?: BlockContent;
};

export type Product = {
  _id: string;
  _type: 'product';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  sku?: string;
  slug?: Slug;
  price?: number;
  mainImages?: Array<
    {
      _key: string;
    } & BlockImage
  >;
  discountInPercent?: number;
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'productCategory';
  };
  availableColor?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'productColor';
  }>;
  availableSize?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'productSize';
  }>;
  brand?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'productBrand';
  };
  numberInStock?: number;
  body?: BlockContent;
};

export type ProductBrand = {
  _id: string;
  _type: 'productBrand';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  mainImage?: BlockImage;
};

export type ProductSize = {
  _id: string;
  _type: 'productSize';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type ProductColor = {
  _id: string;
  _type: 'productColor';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type ProductCategory = {
  _id: string;
  _type: 'productCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Blog
  | BlockContent
  | BlockImage
  | Slug
  | Author
  | BlogCategory
  | UtilityPage
  | Faq
  | TeamMember
  | Product
  | ProductBrand
  | ProductSize
  | ProductColor
  | ProductCategory
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/sanityQueries.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type == 'product' && defined(slug.current)]{  name,  slug,  price,  "imageUrl": mainImages[0].asset -> url,  "imageAlt": mainImages[0].alt,  "colors": availableColor[]->{name},  discountInPercent,  "brand": brand->name }
export type ALL_PRODUCTS_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
  price: number | null;
  imageUrl: string | null;
  imageAlt: string | null;
  colors: Array<{
    name: string | null;
  }> | null;
  discountInPercent: number | null;
  brand: string | null;
}>;
// Variable: PRODUCT_QUERY
// Query: *[_type == 'product' && slug.current == $slug][0]{  name,  slug,  sku,  'category': category->name,  price,  discountInPercent,  'colors': availableColor[]->name,  'sizes': availableSize[]->name,  mainImages[]{    asset->{url},    alt  },  body, }
export type PRODUCT_QUERYResult = {
  name: string | null;
  slug: Slug | null;
  sku: string | null;
  category: string | null;
  price: number | null;
  discountInPercent: number | null;
  colors: Array<string | null> | null;
  sizes: Array<string | null> | null;
  mainImages: Array<{
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  }> | null;
  body: BlockContent | null;
} | null;
// Variable: ALL_BLOGS_QUERY
// Query: *[_type == 'blog' && defined(slug.current)]{  title,  'slug': slug.current,  'author': author->name,  'authorImg': author->mainImage{alt, asset->{url}},  subtitle,  'category': category->name,  publishedAt,  'imageUrl': mainImage.asset->url,  'imageAlt': mainImage.alt,  minRead }
export type ALL_BLOGS_QUERYResult = Array<{
  title: string | null;
  slug: string | null;
  author: string | null;
  authorImg: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  subtitle: string | null;
  category: string | null;
  publishedAt: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
  minRead: number | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == \'product\'\n && defined(slug.current)]{\n  name,\n  slug,\n  price,\n  "imageUrl": mainImages[0].asset -> url,\n  "imageAlt": mainImages[0].alt,\n  "colors": availableColor[]->{name},\n  discountInPercent,\n  "brand": brand->name\n }\n ': ALL_PRODUCTS_QUERYResult;
    "*[_type == 'product'\n && slug.current == $slug][0]{\n  name,\n  slug,\n  sku,\n  'category': category->name,\n  price,\n  discountInPercent,\n  'colors': availableColor[]->name,\n  'sizes': availableSize[]->name,\n  mainImages[]{\n    asset->{url},\n    alt\n  },\n  body,\n }": PRODUCT_QUERYResult;
    "*[_type == 'blog'\n && defined(slug.current)]{\n  title,\n  'slug': slug.current,\n  'author': author->name,\n  'authorImg': author->mainImage{alt, asset->{url}},\n  subtitle,\n  'category': category->name,\n  publishedAt,\n  'imageUrl': mainImage.asset->url,\n  'imageAlt': mainImage.alt,\n  minRead\n }": ALL_BLOGS_QUERYResult;
  }
}
